import { OnInit, EventEmitter, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { NgxSmartModalService } from '../services/ngx-smart-modal.service';
export declare class NgxSmartModalComponent implements OnInit, OnDestroy {
    private ngxSmartModalService;
    private changeDetectorRef;
    closable: boolean;
    escapeAble: boolean;
    identifier: string;
    customClass: string;
    visible: boolean;
    backdrop: boolean;
    force: boolean;
    visibleChange: EventEmitter<boolean>;
    onClose: EventEmitter<any>;
    onCloseFinished: EventEmitter<any>;
    onDismiss: EventEmitter<any>;
    onDismissFinished: EventEmitter<any>;
    onOpen: EventEmitter<any>;
    onEscape: EventEmitter<any>;
    onDataAdded: EventEmitter<any>;
    onDataRemoved: EventEmitter<any>;
    layerPosition: number;
    overlayVisible: boolean;
    private data;
    constructor(ngxSmartModalService: NgxSmartModalService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnDestroy(): void;
    open(top?: boolean): void;
    close(): void;
    dismiss(e: any): void;
    addCustomClass(className: string): void;
    removeCustomClass(className?: string): void;
    isVisible(): boolean;
    hasData(): boolean;
    setData(data: any, force?: boolean): any;
    getData(): any;
    removeData(): void;
    private escapeKeyboardEvent(event);
}
